version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - backend
      - frontend
  client:
    depends_on:
      - app
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL='https://localhost:4000'
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:
